### ISSUE TITLE
FullyPacks (Feed Page)

### ISSUE THREAD

**Issue by tomasohCHOM** [acmcsufoss/fullyhacks#54]
## File location

Here is the file location of the [FullyPacks Component](https://github.com/acmcsufoss/fullyhacks/blob/main/src/components/FeedPage/FullyPacks.tsx), where you can start coding

The file location of the Feed component can be found [here](https://github.com/acmcsufoss/fullyhacks/blob/main/src/components/FeedPage/Feed.tsx), which is mounted in [here](https://github.com/acmcsufoss/fullyhacks/blob/main/src/pages/feed.tsx)

## Design

Refer to [this Figma design](https://www.figma.com/file/NPhRM4yvHp3skLWWXSr7j4/fullyhacks-feed?type=design&node-id=6-72&mode=design&t=v30JkqJlq5XLo62Z-0)

<img src="https://github.com/acmcsufoss/fullyhacks/assets/112128328/6db3f409-4582-4b36-a115-f528a2a74757" width="600" />

[EDIT: Changed Figma design and Figma file url]

## Reference

- All of custom colors, font size is labeled according to [tailwind.config.js](https://github.com/acmcsufoss/fullyhacks/blob/main/tailwind.config.js), feel free to change it since the color was from 2023
- [TailwindCSS home page](https://tailwindcss.com/docs/flex-basis) to learn how to use TailwindCSS for styling

Ex:
```html
<div className='text-light_blue text-3xl font-bold'>
```
will give you light blue text color, font size = 3xl = 2rem according to tailwind.config.js and bolded

## Icons

All of the icons can be imported from [React-icons](https://react-icons.github.io/react-icons/search) (Refer to it to find the icon name)
Ex:
```js
import {AiOutlineSearch} from 'react-icons/ai';
```
Then you can use it as a component and customize color + size

```html
<div className=''>
  <AiOutlineSearch size={34} color='#00000'/>
</div>
```

## Contributing

1. `git checkout main` to position yourself in the main branch first
1. `git pull` for latest change if there's any
1. `git checkout -b "feed-page/prizes"` to create a new branch
1. `npm run format` to run formatter before commit + push your change
1. Assign reviewer before merging code + attach screenshot to make sure it works

**NOTE**: In order to contribute, you must have submitted your application via [this page](fullyhacks.acmcsuf.com/apply) and must have been approved by the Fullyhacks directors. You will also need access to development environmental variables.

**Comment by JeremiahHerring** [comment]
finished - jeremiah
